spring.application.name=tournament

spring.datasource.url=jdbc:postgresql://localhost:5432/tournament_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# spring.jpa.hidernate.ddl-auto=update
spring.sql.init.mode=always