CREATE TABLE IF NOT EXISTS "User" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL UNIQUE,
    "email" TEXT NOT NULL UNIQUE,
    "passwordHash" TEXT NOT NULL,
    -- PLAYER
    -- ORGANIZER
    -- ADMIN
    "role" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

COMMENT ON COLUMN "User"."role" IS 'PLAYER
ORGANIZER
ADMIN';


CREATE TABLE IF NOT EXISTS "GameTypes" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL UNIQUE,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "PlayerProfile" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "gameId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL UNIQUE,
    "nickname" TEXT NOT NULL,
    "description" TEXT,
    "country" TEXT NOT NULL,
    "rating" DECIMAL(5, 2) NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "Team" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "captainId" INTEGER,
    PRIMARY KEY ("id")
);


CREATE TABLE IF NOT EXISTS "TeamMembers" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "playerId" INTEGER NOT NULL,
    "teamId" INTEGER NOT NULL,
    -- CAPTAIN
    -- MEMBER
    "role" TEXT NOT NULL,
    "joinedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id"),
    UNIQUE ("teamId", "playerId")
);

COMMENT ON COLUMN "TeamMembers"."role" IS 'CAPTAIN
MEMBER';


CREATE TABLE IF NOT EXISTS "Tournament" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    -- SOLO
    -- TEAM
    "participantType" TEXT NOT NULL,
    -- OPEN
    -- INVITE
    "access" TEXT NOT NULL,
    "gameType" INTEGER NOT NULL,
    -- DRAFT
    -- REGISTRATION_OPEN
    -- IN_PROGRESS
    -- FINISHED
    -- CANCELLED
    "status" TEXT NOT NULL,
    "organizerId" INTEGER NOT NULL,
    "startDate" TIMESTAMP NOT NULL,
    "registrationDeadline" TIMESTAMP,
    -- Уникальное количество игроков/команд
    "maxParticipants" INTEGER,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id")
);

COMMENT ON COLUMN "Tournament"."participantType" IS 'SOLO
TEAM';
COMMENT ON COLUMN "Tournament"."access" IS 'OPEN
INVITE';
COMMENT ON COLUMN "Tournament"."status" IS 'DRAFT
REGISTRATION_OPEN
IN_PROGRESS
FINISHED
CANCELLED';
COMMENT ON COLUMN "Tournament"."maxParticipants" IS 'Уникальное количество игроков/команд';


CREATE TABLE IF NOT EXISTS "TournamentSoloParticipant" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "playerProfileId" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    -- Используется для формирования сетки.
    "seed" INTEGER NOT NULL,
    "joinedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "finalPlace" INTEGER,
    PRIMARY KEY ("id"),
    UNIQUE ("tournamentId", "playerProfileId")
);

COMMENT ON COLUMN "TournamentSoloParticipant"."seed" IS 'Используется для формирования сетки.';


CREATE TABLE IF NOT EXISTS "TournamentTeamParticipant" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "teamId" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    -- Используется для формирования сетки.
    "seed" INTEGER NOT NULL,
    "joinedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "finalPlace" INTEGER,
    PRIMARY KEY ("id"),
    UNIQUE ("tournamentId", "teamId")
);

COMMENT ON COLUMN "TournamentTeamParticipant"."seed" IS 'Используется для формирования сетки.';


CREATE TABLE IF NOT EXISTS "MatchSolo" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "roundNumber" INTEGER,
    "player1Id" INTEGER NOT NULL,
    "player2Id" INTEGER NOT NULL,
    "winnerPlayerId" INTEGER,
    -- SCHEDULED
    -- IN_PROGRESS
    -- FINISHED
    -- CANCELLED
    "status" TEXT NOT NULL,
    "scheduledAt" TIMESTAMP,
    "nextMatchId" INTEGER,
    PRIMARY KEY ("id")
);

COMMENT ON COLUMN "MatchSolo"."status" IS 'SCHEDULED
IN_PROGRESS
FINISHED
CANCELLED';


CREATE TABLE IF NOT EXISTS "MatchTeam" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "roundNumber" INTEGER,
    "team1Id" INTEGER NOT NULL,
    "team2Id" INTEGER NOT NULL,
    "winnerTeamId" INTEGER,
    -- SCHEDULED
    -- IN_PROGRESS
    -- FINISHED
    -- CANCELLED
    "status" TEXT NOT NULL,
    "scheduledAt" TIMESTAMP,
    "nextMatchId" INTEGER,
    PRIMARY KEY ("id")
);

COMMENT ON COLUMN "MatchTeam"."status" IS 'SCHEDULED
IN_PROGRESS
FINISHED
CANCELLED';


ALTER TABLE "PlayerProfile"
ADD CONSTRAINT "fk_playerprofile_user"
FOREIGN KEY ("userId") REFERENCES "User"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "PlayerProfile"
ADD CONSTRAINT "fk_playerprofile_game"
FOREIGN KEY ("gameId") REFERENCES "GameTypes"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "Team"
ADD CONSTRAINT "fk_team_captain"
FOREIGN KEY ("captainId") REFERENCES "PlayerProfile"("id")
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "TeamMembers"
ADD CONSTRAINT "fk_teammembers_player"
FOREIGN KEY ("playerId") REFERENCES "PlayerProfile"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "TeamMembers"
ADD CONSTRAINT "fk_teammembers_team"
FOREIGN KEY ("teamId") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "Tournament"
ADD CONSTRAINT "fk_tournament_organizer"
FOREIGN KEY ("organizerId") REFERENCES "User"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "Tournament"
ADD CONSTRAINT "fk_tournament_game"
FOREIGN KEY ("gameType") REFERENCES "GameTypes"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "TournamentSoloParticipant"
ADD CONSTRAINT "fk_tsp_tournament"
FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "TournamentSoloParticipant"
ADD CONSTRAINT "fk_tsp_playerprofile"
FOREIGN KEY ("playerProfileId") REFERENCES "PlayerProfile"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "TournamentTeamParticipant"
ADD CONSTRAINT "fk_ttp_tournament"
FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "TournamentTeamParticipant"
ADD CONSTRAINT "fk_ttp_team"
FOREIGN KEY ("teamId") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "MatchSolo"
ADD CONSTRAINT "fk_matchsolo_tournament"
FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "MatchSolo"
ADD CONSTRAINT "fk_matchsolo_player1"
FOREIGN KEY ("player1Id") REFERENCES "PlayerProfile"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "MatchSolo"
ADD CONSTRAINT "fk_matchsolo_player2"
FOREIGN KEY ("player2Id") REFERENCES "PlayerProfile"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "MatchSolo"
ADD CONSTRAINT "fk_matchsolo_winner"
FOREIGN KEY ("winnerPlayerId") REFERENCES "PlayerProfile"("id")
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "MatchSolo"
ADD CONSTRAINT "fk_matchsolo_nextmatch"
FOREIGN KEY ("nextMatchId") REFERENCES "MatchSolo"("id")
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "MatchTeam"
ADD CONSTRAINT "fk_matchteam_tournament"
FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id")
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "MatchTeam"
ADD CONSTRAINT "fk_matchteam_team1"
FOREIGN KEY ("team1Id") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "MatchTeam"
ADD CONSTRAINT "fk_matchteam_team2"
FOREIGN KEY ("team2Id") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "MatchTeam"
ADD CONSTRAINT "fk_matchteam_winner"
FOREIGN KEY ("winnerTeamId") REFERENCES "Team"("id")
ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE "MatchTeam"
ADD CONSTRAINT "fk_matchteam_nextmatch"
FOREIGN KEY ("nextMatchId") REFERENCES "MatchTeam"("id")
ON UPDATE CASCADE ON DELETE SET NULL;