-- 1. Пользователи
CREATE TABLE IF NOT EXISTS "User" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" TEXT NOT NULL,                     -- PLAYER, ORGANIZER, ADMIN
    "country" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);
COMMENT ON COLUMN "User"."role" IS 'PLAYER, ORGANIZER, ADMIN';

-- 2. Типы игр (справочник)
CREATE TABLE IF NOT EXISTS "GameTypes" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY("id")
);

-- 3. Команды (капитан ссылается на пользователя)
CREATE TABLE IF NOT EXISTS "Team" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "captainId" INTEGER,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_team_captain" FOREIGN KEY ("captainId") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 4. Турниры
CREATE TABLE IF NOT EXISTS "Tournament" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL UNIQUE,
    "description" TEXT NOT NULL,
    "participantType" TEXT NOT NULL,          -- SOLO, TEAM
    "access" TEXT NOT NULL,                  -- OPEN, INVITE
    "gameType" INTEGER NOT NULL,
    "status" TEXT NOT NULL,                  -- DRAFT, REGISTRATION_OPEN, IN_PROGRESS, FINISHED, CANCELLED
    "organizerId" INTEGER NOT NULL,
    "startDate" TIMESTAMP NOT NULL,
    "registrationDeadline" TIMESTAMP,
    "maxParticipants" INTEGER,               -- максимальное количество игроков/команд
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY("id"),
    CONSTRAINT "fk_tournament_organizer" FOREIGN KEY ("organizerId") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_tournament_game_type" FOREIGN KEY ("gameType") REFERENCES "GameTypes"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
COMMENT ON COLUMN "Tournament"."participantType" IS 'SOLO, TEAM';
COMMENT ON COLUMN "Tournament"."access" IS 'OPEN, INVITE';
COMMENT ON COLUMN "Tournament"."status" IS 'DRAFT, REGISTRATION_OPEN, IN_PROGRESS, FINISHED, CANCELLED';
COMMENT ON COLUMN "Tournament"."maxParticipants" IS 'Уникальное количество игроков/команд';

-- 5. Игры пользователя (рейтинг по каждой игре)
CREATE TABLE IF NOT EXISTS "UserGames" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "gameId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_usergames_game" FOREIGN KEY ("gameId") REFERENCES "GameTypes"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_usergames_user" FOREIGN KEY ("userId") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "uq_usergames_user_game" UNIQUE ("userId", "gameId")   -- один пользователь – один рейтинг на игру
);

-- 6. Участники команды (связь пользователей с командами)
CREATE TABLE IF NOT EXISTS "TeamMembers" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "playerId" INTEGER NOT NULL,              -- ссылка на User.id (убрано IDENTITY)
    "teamId" INTEGER NOT NULL,
    "role" TEXT NOT NULL,                    -- CAPTAIN, MEMBER
    "joinedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY("id"),
    CONSTRAINT "fk_teammembers_player" FOREIGN KEY ("playerId") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_teammembers_team" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "uq_teammembers_player_team" UNIQUE ("playerId", "teamId")   -- игрок может быть в команде только один раз
);
COMMENT ON COLUMN "TeamMembers"."role" IS 'CAPTAIN, MEMBER';

-- 7. Участники соло-турнира
CREATE TABLE IF NOT EXISTS "TournamentSoloParticipant" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "playerProfileId" INTEGER,               -- ссылка на User.id
    "status" TEXT NOT NULL,
    "seed" INTEGER NOT NULL,                 -- для формирования сетки
    "joinedAt" TIMESTAMP NOT NULL,
    "finalPlace" INTEGER,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_soloparticipant_tournament" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_soloparticipant_player" FOREIGN KEY ("playerProfileId") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
COMMENT ON COLUMN "TournamentSoloParticipant"."seed" IS 'Используется для формирования сетки.';

-- 8. Участники командного турнира
CREATE TABLE IF NOT EXISTS "TournamentTeamParticipant" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "teamId" INTEGER NOT NULL,
    "status" TEXT NOT NULL,
    "seed" INTEGER NOT NULL,                 -- для формирования сетки
    "joinedAt" TIMESTAMP NOT NULL DEFAULT NOW(),   -- исправлено: было "joinedId"
    "finalPlace" INTEGER,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_teamparticipant_tournament" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_teamparticipant_team" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
COMMENT ON COLUMN "TournamentTeamParticipant"."seed" IS 'Используется для формирования сетки.';

-- 9. Матчи соло
CREATE TABLE IF NOT EXISTS "MatchSolo" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "roundNumber" INTEGER,
    "player1Id" INTEGER NOT NULL,
    "player2Id" INTEGER NOT NULL,
    "winnerPlayerId" INTEGER,
    "status" TEXT NOT NULL,                  -- SCHEDULED, IN_PROGRESS, FINISHED, CANCELLED
    "scheduledAt" TIMESTAMP,
    "nextMatchId" INTEGER,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_matchsolo_tournament" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchsolo_player1" FOREIGN KEY ("player1Id") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchsolo_player2" FOREIGN KEY ("player2Id") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchsolo_winner" FOREIGN KEY ("winnerPlayerId") REFERENCES "User"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchsolo_next" FOREIGN KEY ("nextMatchId") REFERENCES "MatchSolo"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
COMMENT ON COLUMN "MatchSolo"."status" IS 'SCHEDULED, IN_PROGRESS, FINISHED, CANCELLED';

-- 10. Матчи команд
CREATE TABLE IF NOT EXISTS "MatchTeam" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tournamentId" INTEGER NOT NULL,
    "roundNumber" INTEGER,
    "team1Id" INTEGER NOT NULL,
    "team2Id" INTEGER NOT NULL,
    "winnerTeamId" INTEGER,
    "status" TEXT NOT NULL,                  -- SCHEDULED, IN_PROGRESS, FINISHED, CANCELLED
    "scheduledAt" TIMESTAMP,
    "nextMatchId" INTEGER,
    PRIMARY KEY("id"),
    CONSTRAINT "fk_matchteam_tournament" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchteam_team1" FOREIGN KEY ("team1Id") REFERENCES "Team"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchteam_team2" FOREIGN KEY ("team2Id") REFERENCES "Team"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchteam_winner" FOREIGN KEY ("winnerTeamId") REFERENCES "Team"("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT "fk_matchteam_next" FOREIGN KEY ("nextMatchId") REFERENCES "MatchTeam"("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
COMMENT ON COLUMN "MatchTeam"."status" IS 'SCHEDULED, IN_PROGRESS, FINISHED, CANCELLED';